import '@testing-library/jest-dom'
import { vi } from 'vitest'

// Mock window.electronAPI for tests that use IPC
const mockElectronAPI = {
  getAppVersion: vi.fn().mockResolvedValue('1.3.2'),
  getPlatform: vi.fn().mockResolvedValue('darwin'),
  minimizeWindow: vi.fn(),
  maximizeWindow: vi.fn(),
  closeWindow: vi.fn(),
  isMaximized: vi.fn().mockResolvedValue(false),
  database: {
    getAIProviders: vi.fn().mockResolvedValue([]),
    saveAIProvider: vi.fn().mockResolvedValue({}),
    updateAIProvider: vi.fn().mockResolvedValue({}),
    getConversations: vi.fn().mockResolvedValue([]),
    getConversation: vi.fn().mockResolvedValue(null),
    saveConversation: vi.fn().mockResolvedValue({}),
    updateConversation: vi.fn().mockResolvedValue({}),
    deleteConversation: vi.fn().mockResolvedValue(true),
    addMessageToConversation: vi.fn().mockResolvedValue({}),
    updateConversationTitle: vi.fn().mockResolvedValue({}),
    updateConversationModel: vi.fn().mockResolvedValue({}),
    getSetting: vi.fn().mockResolvedValue(null),
    setSetting: vi.fn().mockResolvedValue({}),
    getSettings: vi.fn().mockResolvedValue([]),
    getAIModels: vi.fn().mockResolvedValue([]),
    saveAIModel: vi.fn().mockResolvedValue({}),
    deleteAIModels: vi.fn().mockResolvedValue(true),
    testAIProvider: vi.fn().mockResolvedValue({ success: true }),
    refreshAIModels: vi.fn().mockResolvedValue([]),
    query: vi.fn().mockResolvedValue([]),
    execute: vi.fn().mockResolvedValue({ changes: 0 }),
  },
  wisdom: {
    upload: vi.fn().mockResolvedValue({}),
    search: vi.fn().mockResolvedValue([]),
    list: vi.fn().mockResolvedValue([]),
    delete: vi.fn().mockResolvedValue(true),
    update: vi.fn().mockResolvedValue({}),
    reindex: vi.fn().mockResolvedValue({}),
    getEmbeddingProviders: vi.fn().mockResolvedValue([]),
    setEmbeddingProvider: vi.fn().mockResolvedValue({}),
    validateIndexing: vi.fn().mockResolvedValue({}),
    massiveReindex: vi.fn().mockResolvedValue({}),
    cleanDatabase: vi.fn().mockResolvedValue({}),
    getCatalog: vi.fn().mockResolvedValue([]),
    indexFromCatalog: vi.fn().mockResolvedValue({}),
    getVectorGraph: vi.fn().mockResolvedValue({ nodes: [], edges: [] }),
    getRAGHealth: vi.fn().mockResolvedValue({}),
    getVectorClusters: vi.fn().mockResolvedValue([]),
    selectFolder: vi.fn().mockResolvedValue(null),
    getFolderStructure: vi.fn().mockResolvedValue({}),
    bulkUploadDocuments: vi.fn().mockResolvedValue({}),
    checkOllamaConnection: vi.fn().mockResolvedValue(false),
    onUploadProgress: vi.fn().mockReturnValue(() => {}),
  },
  hydraulic: {
    classifyQuery: vi.fn().mockResolvedValue({}),
    extractParameters: vi.fn().mockResolvedValue({}),
    identifyRegulations: vi.fn().mockResolvedValue({}),
    calculate: vi.fn().mockResolvedValue({}),
    getFormulas: vi.fn().mockResolvedValue([]),
    getFormulasByCategory: vi.fn().mockResolvedValue([]),
    searchKnowledge: vi.fn().mockResolvedValue([]),
    getRegulations: vi.fn().mockResolvedValue([]),
    createProject: vi.fn().mockResolvedValue({}),
    getProject: vi.fn().mockResolvedValue(null),
    listProjects: vi.fn().mockResolvedValue([]),
    updateProject: vi.fn().mockResolvedValue({}),
    deleteProject: vi.fn().mockResolvedValue(true),
    saveCalculation: vi.fn().mockResolvedValue({}),
    enhancedChat: vi.fn().mockResolvedValue({}),
  },
  wntr: {
    loadINPFile: vi.fn().mockResolvedValue(null),
    loadINPFromPath: vi.fn().mockResolvedValue(null),
    saveINPFile: vi.fn().mockResolvedValue(null),
    runSimulation: vi.fn().mockResolvedValue({}),
    runHydraulicSimulation: vi.fn().mockResolvedValue({}),
    analyzeNetwork: vi.fn().mockResolvedValue({}),
    exportJSON: vi.fn().mockResolvedValue(null),
  },
  chat: {
    sendMessage: vi.fn().mockResolvedValue({}),
  },
  auth: {
    microsoftLogin: vi.fn().mockResolvedValue({}),
    googleLogin: vi.fn().mockResolvedValue({}),
    logout: vi.fn().mockResolvedValue(true),
    getTokens: vi.fn().mockResolvedValue(null),
    refreshToken: vi.fn().mockResolvedValue(null),
    validateToken: vi.fn().mockResolvedValue(false),
    getUserProfile: vi.fn().mockResolvedValue(null),
    getActiveProfiles: vi.fn().mockResolvedValue([]),
    getConnectionStatus: vi.fn().mockResolvedValue({}),
    testConnection: vi.fn().mockResolvedValue(false),
  },
  files: {
    selectFile: vi.fn().mockResolvedValue(null),
    readFile: vi.fn().mockResolvedValue(''),
    writeFile: vi.fn().mockResolvedValue(true),
  },
  dialog: {
    showOpenDialog: vi.fn().mockResolvedValue({ canceled: true, filePaths: [] }),
    showSaveDialog: vi.fn().mockResolvedValue({ canceled: true }),
  },
  onNewChat: vi.fn().mockReturnValue(() => {}),
  onOpenSettings: vi.fn().mockReturnValue(() => {}),
  onDisableSatelliteMode: vi.fn().mockReturnValue(() => {}),
}

// @ts-expect-error - mock for testing
globalThis.window.electronAPI = mockElectronAPI
// @ts-expect-error - mock for testing
globalThis.window.electron = true
